#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x2C0754B2CE0692F3 (tomaz@tomaz.me)
#
Name     : apache-libcloud
Version  : 2.6.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/08/c7/951755bbfecf5eab30448062ba706e71a1f2e8b51413916c2dcea8f2ad41/apache-libcloud-2.6.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/08/c7/951755bbfecf5eab30448062ba706e71a1f2e8b51413916c2dcea8f2ad41/apache-libcloud-2.6.0.tar.gz
Source1 : https://files.pythonhosted.org/packages/08/c7/951755bbfecf5eab30448062ba706e71a1f2e8b51413916c2dcea8f2ad41/apache-libcloud-2.6.0.tar.gz.asc
Summary  : A standard Python library that abstracts away differences among multiple cloud provider APIs. For more information and documentation, please see http://libcloud.apache.org
Group    : Development/Tools
License  : Apache-2.0
Requires: apache-libcloud-license = %{version}-%{release}
Requires: apache-libcloud-python = %{version}-%{release}
Requires: apache-libcloud-python3 = %{version}-%{release}
Requires: requests
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : requests
BuildRequires : tox
BuildRequires : virtualenv

%description
Apache Libcloud - a unified interface for the cloud
====================================================

%package license
Summary: license components for the apache-libcloud package.
Group: Default

%description license
license components for the apache-libcloud package.


%package python
Summary: python components for the apache-libcloud package.
Group: Default
Requires: apache-libcloud-python3 = %{version}-%{release}

%description python
python components for the apache-libcloud package.


%package python3
Summary: python3 components for the apache-libcloud package.
Group: Default
Requires: python3-core

%description python3
python3 components for the apache-libcloud package.


%prep
%setup -q -n apache-libcloud-2.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567175385
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/apache-libcloud
cp LICENSE %{buildroot}/usr/share/package-licenses/apache-libcloud/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/apache-libcloud/NOTICE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/apache-libcloud/LICENSE
/usr/share/package-licenses/apache-libcloud/NOTICE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
